### ISSUE TITLE
is that able to run on cpu?

### ISSUE THREAD

**Issue by jinfagang** [microsoft/StyleSwin#5]
is that able to run on cpu?

**Comment by ForeverFancy** [comment]
Yes. For inference, just try to set all the devices to cpu and set args.distributed to False, and then the model is able to run on cpu device. We do not recommend using cpu for training due to the unacceptable speed.

**Comment by jinfagang** [comment]
@ForeverFancy I just want inference, but I saw there are some ops using cuda kernel, does it effect?

**Comment by ForeverFancy** [comment]
When detecting the device of input is cpu, the ops would not use the cuda kernel, but run the cpu code instead. See [fused_act.py#L93](https://github.com/microsoft/StyleSwin/blob/main/op/fused_act.py#L93) and [upfirdn2d.py#L147](https://github.com/microsoft/StyleSwin/blob/main/op/upfirdn2d.py#L147). Besides, you could also remove the cuda kernel part and reserve cpu part to ensure the whole code is runnable on cpu device.

**Comment by jinfagang** [comment]
@ForeverFancy thank u, that's very helpful. Did u test styles win speed compares with stylegan on same device and same input resolution? which one is faster?

**Comment by ForeverFancy** [comment]
We have tested StyleSwin and StyleGAN2 on 1024 resolution. The FLOPs of StyleGAN2 and StyleSwin are 74.27B and 50.90B respectively, and the throughput of StyleGAN2 and StyleSwin are 40.05 imgs/sec and 11.05 imgs/sec respectively on V100 GPU. And we think the gap between the theoretical FLOPs and the throughput in practice is mainly because that the vision transformers have not been sufficiently optimized as ConvNets, and we believe future optimization will democratize the usage of transformers as they exhibit lower theoretical FLOPs.
